# Generated by Django 4.1 on 2023-12-13 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, unique=True, verbose_name='Full Name')),
                ('customer_type', models.CharField(max_length=20, verbose_name='Customer Type')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, null=True, verbose_name='Author')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Image Description')),
                ('image_url', models.URLField(default='https://www.pexels.com/', verbose_name='Source')),
                ('category', models.CharField(choices=[('PH', 'Photo'), ('ART', 'Art')], max_length=10, verbose_name='Type')),
                ('theme', models.CharField(choices=[('MT', 'Mountain'), ('LK', 'Lake'), ('PLR', 'Polar'), ('FRST', 'Forest'), ('TR', 'Tree'), ('FLWR', 'Flowers')], max_length=20, verbose_name='Theme')),
                ('image', models.ImageField(default='images/flower-gold-mohar.jpg', upload_to='images', verbose_name='Image')),
                ('status', models.CharField(choices=[('AVL', 'Available'), ('OOPS', 'Out of Stock')], default='AVL', max_length=30, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now=True, verbose_name='Date of Order')),
                ('order_status', models.CharField(choices=[('SHIP', 'Shipped'), ('DEL', 'Delivered')], max_length=30, verbose_name='Order Status')),
                ('customer_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to='photostore.cart')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_exchanged', to='photostore.product')),
            ],
        ),
    ]
