# Generated by Django 4.1 on 2023-11-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=128, verbose_name='Full Name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=72, verbose_name='Author (full name)')),
                ('type', models.CharField(choices=[('PH', 'Photo'), ('ART', 'Art')], max_length=10, verbose_name='Type')),
                ('theme', models.CharField(choices=[('mountain', 'Mountain'), ('lake', 'Lake'), ('polar', 'Polar'), ('forest', 'Forest'), ('tree', 'Tree'), ('flowers', 'Flowers')], max_length=20, verbose_name='Theme')),
                ('size', models.CharField(choices=[('L', 'Big'), ('M', 'Medium'), ('S', 'Small')], max_length=10, verbose_name='Resolution')),
                ('item_url', models.URLField(max_length=250, unique=True, verbose_name='URL')),
                ('status', models.CharField(choices=[('AVL', 'Available'), ('OOPS', 'Out of Stock')], max_length=30, verbose_name='Status')),
            ],
        ),
    ]
