# Generated by Django 4.1 on 2023-11-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photostore', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Image Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Title'),
        ),
    ]
