# Generated by Django 4.1 on 2023-11-03 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photostore', '0003_product_description_product_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=128, unique=True, verbose_name='Full Name')),
                ('type', models.CharField(max_length=20, verbose_name='Customer Type')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_information', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now=True, verbose_name='Date of Order')),
                ('order_status', models.CharField(choices=[('PEN', 'Pending'), ('SHIP', 'Shipped'), ('DEL', 'Delivered')], max_length=30, verbose_name='Order Status')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_data', to='photostore.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Image Description')),
                ('type', models.CharField(choices=[('PH', 'Photo'), ('ART', 'Art')], max_length=10, verbose_name='Type')),
                ('theme', models.CharField(choices=[('mountain', 'Mountain'), ('lake', 'Lake'), ('polar', 'Polar'), ('forest', 'Forest'), ('tree', 'Tree'), ('flowers', 'Flowers')], max_length=20, verbose_name='Theme')),
                ('size', models.CharField(choices=[('L', 'Big'), ('M', 'Medium'), ('S', 'Small')], max_length=10, verbose_name='Resolution')),
                ('item_url', models.URLField(max_length=250, unique=True, verbose_name='URL')),
                ('status', models.CharField(choices=[('AVL', 'Available'), ('OOPS', 'Out of Stock')], max_length=30, verbose_name='Status')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='author_fullname', to='photostore.customers', to_field='fullname')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_data', to='photostore.orders'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='product_status', to='photostore.products'),
        ),
    ]
