# Generated by Django 4.1 on 2023-11-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photostore', '0004_customers_orderdetails_orders_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='barter_exchange',
            field=models.BooleanField(default=False, help_text='Clarifies if customer exchanged photos or not', verbose_name='Photo Exchanged ?'),
        ),
    ]
