# Generated by Django 4.1 on 2023-11-06 12:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photostore', '0005_orders_barter_exchange'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='OrderDetails',
            new_name='OrderDetail',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
