# Generated by Django 4.1 on 2023-11-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photostore', '0006_rename_customers_customer_rename_orders_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='item_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/art-mountain.jfif', upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='theme',
            field=models.CharField(choices=[('MT', 'Mountain'), ('LK', 'Lake'), ('PLR', 'Polar'), ('FRST', 'Forest'), ('TR', 'Tree'), ('FLWR', 'Flowers')], max_length=20, verbose_name='Theme'),
        ),
    ]
