# Generated by Django 4.1 on 2023-11-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photostore', '0008_alter_product_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fullname',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='type',
            new_name='user_type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='category',
        ),
    ]
