# Generated by Django 4.1 on 2023-11-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photostore', '0009_rename_fullname_customer_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user_type',
            new_name='customer_type',
        ),
    ]
