# Generated by Django 4.1 on 2023-11-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photostore', '0011_auto_20231114_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(max_length=100, null=True, verbose_name='Author'),
        ),
    ]
