# Generated by Django 4.1 on 2023-11-30 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photostore', '0013_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_summary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_purchases', to='photostore.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='barter_exchange',
            field=models.BooleanField(default=False, help_text='Clarifies if customer exchanged photos or not', verbose_name='Photo Exchange'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_history', to='photostore.customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/flower-gold-mohar.jpg', upload_to='images', verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ManyToManyField(blank=True, related_name='shipped_products', to='photostore.product')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='items_purchased',
            field=models.ManyToManyField(blank=True, related_name='product_inventory', to='photostore.cart'),
        ),
    ]
