# Generated by Django 4.1 on 2023-12-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photostore', '0015_remove_cart_item_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('AVL', 'Available'), ('OOPS', 'Out of Stock')], default='AVL', max_length=30, verbose_name='Status'),
        ),
    ]
