# Generated by Django 4.1 on 2023-12-05 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photostore', '0021_remove_cart_user_cart_customer_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='potential_customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
