# Generated by Django 4.1 on 2023-12-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photostore', '0022_alter_cart_customer_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='items_purchased',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to='photostore.cart'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order_summary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_purchases', to='photostore.order'),
        ),
    ]
