# Generated by Django 4.1 on 2023-12-07 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photostore', '0023_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='barter_exchange',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_exchanged', to='photostore.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('SHIP', 'Shipped'), ('DEL', 'Delivered')], max_length=30, verbose_name='Order Status'),
        ),
    ]
