# Generated by Django 4.1 on 2023-12-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photostore', '0025_delete_orderdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='potential_customers', to='photostore.customer'),
        ),
    ]
