# Generated by Django 4.1 on 2023-11-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='login_name',
        ),
    ]
