# Generated by Django 4.1 on 2023-11-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='customer_type',
            field=models.CharField(choices=[('Art', 'Artist'), ('Photography', 'Photographer'), ('Curiosity', 'Enthusiast')], max_length=20, verbose_name='Profession/Hobby'),
        ),
    ]
