# Generated by Django 4.1 on 2023-11-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_customer_type_userprofile_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('Designer', 'Artist'), ('Shutterbug', 'Photographer'), ('Aficionado', 'Enthusiast')], max_length=20, verbose_name='Profession/Hobby'),
        ),
    ]
