services:
  - type: web
    name: ecommstore
    env:  python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: "gunicorn ecommstore.wsgi:application"
    envVars:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_SETTINGS_MODULE: "ecommstore.settings"
    staticPublishPath: "staticfiles"
    autoDeploy: true