services:
  - type: web
    name: ecommstore
    env:  python
    buildCommand: "echo 'Build commands executed!'"
    startCommand: "gunicorn ecommstore.ecommstore.wsgi:application"
    envVars:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_SETTINGS_MODULE: "ecommstore.ecommstore.settings"
    staticPublishPath: "ecommstore/staticfiles"
    autoDeploy: true